language: node_js
node_js: "node"
script: npm run prepare
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: prepared
  on:
    branch: master
cache:
  directories:
    - node_modules
